# Generated by Django 4.2 on 2023-07-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_aktyor_jins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kino',
            name='yil',
            field=models.DateField(null=True),
        ),
    ]
