# Generated by Django 4.2 on 2023-07-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_kino_yil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kino',
            name='davomiylik',
            field=models.DurationField(null=True),
        ),
    ]
