# Generated by Django 4.2 on 2023-07-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_kino_davomiylik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kino',
            name='davomiylik',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kino',
            name='yil',
            field=models.DateField(blank=True, null=True),
        ),
    ]
